name: 'adventureworks'
version: '1.0.0'
config-version: 2

profile: 'adventureworks'

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  adventureworks:
    staging:
      +materialized: view
      +schema: staging
    mart:
      +materialized: table
    utils:
      +materialized: table

seeds:
  adventureworks:
    +schema: mart
